### ISSUE TITLE
"SYMBOLIC EXECUTION TIMEOUT"

### ISSUE THREAD

**Issue by fulldecent** [smartbugs/smartbugs-results#2]
"SYMBOLIC EXECUTION TIMEOUT" is not an indicative result.

This is shown in some of the outputs as a failed test, but this is not actually a failed test.

**Comment by jff** [comment]
Hi @fulldecent, could you please elaborate on what you mean by "failed test"? I have noticed that that result appears in, for example, some of Osiris's logs. However, in our metadata files, we do not consider the result as a vulnerability or error.

**Comment by fulldecent** [comment]
Here was one of them https://github.com/smartbugs/smartbugs-results/blob/f7b1728df62740f7e043f8f86645ad3a60465793/results/honeybadger/icse20/0x7dcde80b9e6eaac35cd5e0225f17cf8a418314cc/result.log

Got it, my bad. I had thought that status result was causing the log to go in the repo.
